Repository ebu/ebucoreplus, pull requests merged in 2025-07, with the labels that each got.

#415 Fix for 411 typo
  ontology/EBUCorePlus/ebucoreplus.owl
Labels: documentation

#444 Fix agent subclassing
  ontology/EBUCorePlus/ebucoreplus.owl
Labels: enhancement

#447 Remove unused and undocumented classes ec:BMEssence and ec:BMTemplate
  ontology/EBUCorePlus/ebucoreplus.owl
Labels: documentation, enhancement
